### ISSUE TITLE
Weird result

### ISSUE THREAD

**Issue by Kim9878** [shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting#1]
Hello, when I tested the davis video with pretrained model, I got this weird color result. I don't know how it happened at inpainting area, can you tell me how to solve this? Thank you! 
![f9](https://user-images.githubusercontent.com/30254494/63943434-3db07d00-caa2-11e9-9354-bc530d27c72f.jpg)

**Comment by shleecs** [comment]
Hello,  
In our method, some artifacts occurred for some cases (ex: difficult to align frames of high depth variation using affine transformation / large regions are invisible during the entire sequence due to occlusion).
