### ISSUE TITLE
'A_Regressor' Question

### ISSUE THREAD

**Issue by csqiangwen** [shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting#10]
Thanks for your nice work!
I have one question [here](https://github.com/shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting/blob/master/models/CPNet_model.py#L80-L81).
Why the 'A_Regressor'  initialized the 'conv6a' and 'conv6b' but it did not use them in the forward function?

**Comment by shleecs** [comment]
Thank you for your interest in our works.

It is a minor error while I modify it to implement the final version.

I will update the bug-free code.

Thank you.

Best regards, 
Sungho
