### ISSUE TITLE
The error in the code

### ISSUE THREAD

**Issue by Lucxin** [shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting#11]
when obtaining the encoder features of the target frame, the input of the encoder of the copy network is frame and hole(1 represents the hole region),
`       c_feat_ = [self.Encoder(frame, hole)]`

however, when obtaining the features of the aligned frame, the input is aligned frame and the valid maps(1 represents the valid region)
`c_feat_.append(self.Encoder(aligned_r, aligned_v))`

I think the input should be consistent. I don’t know if what I understand is correct?

**Comment by shleecs** [comment]
Thank you for your interest in our works.

It is a minor error while I modify it to implement the release version.

I will update the bug-free code. (It should be 1. - aligned_v.)

Thank you.

Best regards,
Sungho
