### ISSUE TITLE
About training codes

### ISSUE THREAD

**Issue by Zealoe** [shleecs/Copy-and-Paste-Networks-for-Deep-Video-Inpainting#2]
Your work is very impressive. Could you please release the training codes? I want to learn more details.

**Comment by emilysun201309** [comment]
Any updates on this?

**Comment by shleecs** [comment]
Hello, 
Thank you for your interest about our works.
We are so sorry that couldn't release our training code because of the policy with industrial collaboration.
If you have question for our works during implementation, please e-mail to us. 
Thank you!
